<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobBoard.Application\JobBoard.Application.csproj" />
    <ProjectReference Include="..\JobBoard.Infrastructure\JobBoard.Infrastructure.csproj" />
    <ProjectReference Include="..\JobBoard.Domain\JobBoard.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\JobBoard.Infrastructure\Data\Seed\jobs.json"
             Link="Data\Seed\jobs.json"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
